######################################
# Service definitions for Prometheus #
# monitors                           #
######################################

services:
  # Monitors IRC servers
  irc_agent:
    image: ghcr.io/dgl/ircd_exporter
    container_name: irc_agent
    restart: always
    environment:
      - PIE_IRC.SERVER=${AGENT_IRC_PINEWOOD}
    networks:
      - mainNet

  # SNMP exporter
  snmp_agent:
    image: prom/snmp-exporter
    container_name: snmp_agent
    restart: unless-stopped
    command: "--log.level=debug --config.file=/etc/snmp_exporter/snmp.yml "
    networks:
      - mainNet
