######################################
# Service definitions for Prometheus #
# monitors                           #
######################################

services:
  # Monitors IRC servers
  irc_agent:
    image: ghcr.io/dgl/ircd_exporter
    container_name: irc_agent
    restart: always
    environment:
      - PIE_IRC.SERVER=${AGENT_IRC_PINEWOOD}
    networks:
      - mainNet
