include:
  - networks.yml
  - volumes.yml
  
  - agents/agents.yml

  # Grafana
  - path: grafana/compose.yml
    env_file:
      # Default values
      - .env

      # Grafana specifics
      - grafana/.grafana.env

services:
  host-statistics:
    extends:
      file: ../../services/node_exporter/compose.yml
      service: statistics
    container_name: host_statistics

  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    container_name: yggdrasil
    network_mode: "host"

  # mycelium:
    # extends:
      # file: ../../services/mycelium/compose.yml
      # service: mycelium
    # container_name: mycelium
    # network_mode: "host"

  # Statistics collector
  prometheus:
    extends:
      file: ../../services/prometheus/compose.yml
      service: prometheus
    build:
      context: prometheus/
    depends_on:
      - irc_agent
      - snmp_agent
    container_name: prometheus
    networks:
      - mainNet
    volumes:
      - prometheus_data:/prometheus:z
    # So that all URLs generated, like links, are to
    # our reverse proxy's route
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=/prometheus/"

  # TODO: Add Caddy with `prometheus:9090` proxy_pass

  # Logging collector
  loki:
    extends:
      file: ../../services/loki/compose.yml
      service: loki
    build:
      context: loki/
    user: ${USER_UID}:${USER_GID}
    container_name: loki
    networks:
      - mainNet
    command:
      - "-config.file=/config.yaml"
    # volumes:
      # - /etc/loki

  # Alloy (syslog listener)
  alloy:
    build:
      context: alloy/
    # TODO: Seems inaffective
    user: ${USER_UID}:${USER_GID}
    container_name: alloy
    networks:
      - mainNet
    depends_on:
      - loki
    ports:
      # Syslog listener for Mikrotik's
      - :::3333:3333/tcp
      - :::3333:3333/udp
      
      # - 3333:3333/udp

      # Alloy port (for Grafana/Loki (consumer) to connect to)
      # - 12345:12345/tcp
    command:
      # TODO: Do we need this? - for web UI???
      - "run"
      - "--server.http.listen-addr=[::]:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "--stability.level=experimental"
      - "/etc/alloy/config.alloy"
    volumes:
      # Storage for data
      - "${ALLOY_STORAGE}:/var/lib/alloy:z"

  # TODO: caddy definition and let us copy our caddy file
  # over using a custom image rather. This will allow us
  # to rebuild with a new configuration then and not
  # have to maintain it within a mount-point.
  web:
    container_name: web
    build:
      context: web
    depends_on:
      - prometheus # TODO: Why?
      - grafana
    networks:
      - mainNet
    environment:
      - DOMAIN=${CADDY_DOMAIN}
    ports:
      - "[::]:80:80/tcp"
      - "[::]:80:80/udp" # TODO: Does quick run on non-HTTPS?
      - "[::]:443:443/tcp"
      - "[::]:443:443/udp"
