services:
  unbound:
    build:
      context: ./
    restart: unless-stopped
    volumes:
      # Directory containing control socket
      - "${UNBOUND_CTL_DIR}:/ctl"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
