services:
  unbound:
    build:
      context: unbound/
    restart: unless-stopped
    # volumes:
      # Makes timezone and time information available
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro

      # Directory containing control socket
      - "${UNBOUND_CTL_DIR}:/ctl"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
