networks:
  retNet:
    driver: bridge
    name: retNet
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492b:fc7f::/48

services:
  lxmd:
    container_name: lxmd
    restart: unless-stopped
    depends_on:
      - reticulum
    build:
      context: ../../../images/lxmd
    environment:
      # AutoPeering over link-local didn't work
      # if you didn't make startup wait a little
      # bit (clearly for some Docker networking interfaces
      # to properly initialize)
      #
      - SLEEP_TIME=5
    volumes:
      # Configuration and storage for lxmd
      - ${LXMD_DATA_PATH}:/data:z
      
      # Local RNS instance configuration path
      - ${LXMD_RNS_PATH}:/rns:z
    user: ${USER_UID}:${USER_GID}
    networks:
      - retNet

  reticulum:
    container_name: reticulum
    restart: unless-stopped
    build:
      context: ../../../images/reticulum
      args:
        # This platform cannot use
        # the crypto library, hence
        # we must use the `rnspure`
        # package
        - PURE_INSTALL=false

        # If IPv6 should be preferred
        # whenever getaddrinfo() is
        # used
        - GAI_PREFER_IPV6=true
    environment:
      # AutoPeering over link-local didn't work
      # if you didn't make startup wait a little
      # bit (clearly for some Docker networking interfaces
      # to properly initialize)
      - SLEEP_TIME=5
    volumes:
      # Reticulum configuration and storage directory
      - ${RETICULUM_DATA_PATH}:/data:z
    user: ${USER_UID}:${USER_GID}
    group_add:
      # On container-side the device node
      # (for the RNode) will be mounted with
      # GID 20. Hence ensure we add that to
      # the effective GID supplementary set
      # so that we have permissions to interact
      # with that device
      - 20
    devices:
      # Add RNode devices here
      - /dev/ttyACM0:/dev/rnode1:rwm
    networks:
      - retNet
    ports:
      - :::4242:4242/tcp # TCP server interface port
      - :::4242:4242/udp # UDP server interface port
