services:
  homesteader_relay:
    build:
      context: homesteader
    container_name: homesteader_relay
    restart: unless-stopped
    volumes:
      # Path to relay configuration file
      - /mnt/datadisk/volumes/nostr/homesteader.toml:/usr/src/app/config.toml:ro
    network_mode: service:homesteader_db
    
  homesteader_db:
    image: postgres:16.4
    container_name: homesteader_db

    # The container will create a user with this
    # UID/GID pair. This matches MY host, make them
    # match your host. This makes files created in
    # the mountpoint easily accessible for us
    user: ${USER_UID}:${USER_GID}

    environment:
      - POSTGRES_DB=nostr
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - PGDATA=/var/lib/postgresql/data
    restart: unless-stopped
    volumes:
      - ${NOSTR_HOMESTEADER_DB_PATH}:/var/lib/postgresql/data:z
    networks:
      ipv6_pool_net:
        ipv6_address: ${NOSTR_RELAY_HOMESTEADER_ADDR}
      yggdrasil_net:
        ipv6_address: ${NOSTR_RELAY_HOMESTEADER_ADDR_Y}
    ports:
      # Expose (firewall) on behalf of `personal_relay`
      - 7000/tcp