


services:
  ephemeral_relay:
    build:
      context: nostr/
      args:
        - CARGO_LOG=trace
    container_name: ephemeral_relay
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      # Path to relay configuration file
      - /mnt/datadisk/volumes/nostr/ephemeral.toml:/usr/src/app/config.toml:ro

      #  Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  homesteader_relay:
    depends_on:
      - homesteader_db
    build:
      context: nostr/
      args:
        - CARGO_LOG=trace
    container_name: homesteader_relay
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      # Path to relay configuration file
      - /mnt/datadisk/volumes/nostr/homesteader.toml:/usr/src/app/config.toml:ro

  ephemeral_restarter:
    container_name: ephemeral_restarter
    depends_on:
      - ephemeral_relay
    build:
      context: restarter/
    restart: always
    environment:
      - SLEEP_SECS=604800
      - CONTAINER_NAME=ephemeral_relay
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  homesteader_db:
    image: postgres:16.4
    container_name: homesteader_db

    # The container will create a user with this
    # UID/GID pair. This matches MY host, make them
    # match your host. This makes files created in
    # the mountpoint easily accessible for us
    user: "1000:1000"

    environment:
      - POSTGRES_DB=nostr
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - PGDATA=/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      - /mnt/datadisk/volumes/nostr/homesteader_data:/var/lib/postgresql/data

  personal_db:
    image: postgres:16.4
    container_name: personal_db

    # The container will create a user with this
    # UID/GID pair. This matches MY host, make them
    # match your host. This makes files created in
    # the mountpoint easily accessible for us
    user: "1000:1000"

    environment:
      - POSTGRES_DB=nostr
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - PGDATA=/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      - ${NOSTR_PERSONAL_DB_PATH}:/var/lib/postgresql/data:z

  personal_relay:
    depends_on:
      - personal_db
    build:
      context: nostr/
      args:
        - CARGO_LOG=trace
    container_name: personal_relay
    restart: unless-stopped
    network_mode: service:personal_proxy
    volumes:
      # Path to relay configuration file
      - ${NOSTR_PERSONAL_CONFIG_PATH}:/usr/src/app/config.toml:ro,z

  personal_proxy:
    build:
      context: ../flat
    container_name: personal_proxy
    restart: unless-stopped
    environment:
      - "DOMAIN=${NOSTR_RELAY_PERSONAL_DOMAIN}"
      # - "WHERE_TO_ADDR=gitea_old_anubis" (FIXME: Lookup fails to resolve by Caddy, not sure why)
      - "WHERE_TO_ADDR=[::1]"
      - "WHERE_TO_PORT=7000"
      - "DEBUG_LEVEL=INFO"
    networks:
      ipv6_pool_net:
        ipv6_address: ${NOSTR_RELAY_PERSONAL_ADDR}