include:
  - personal.yml
  - ephemeral.yml

services:
  homesteader_relay:
    depends_on:
      - homesteader_db
    image: ghcr.io/deavmi/nostr-rs-relay:master
    container_name: homesteader_relay
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      # Path to relay configuration file
      - /mnt/datadisk/volumes/nostr/homesteader.toml:/usr/src/app/config.toml:ro

  ephemeral_restarter:
    container_name: ephemeral_restarter
    depends_on:
      - ephemeral_relay
    build:
      context: restarter/
    restart: always
    environment:
      - SLEEP_SECS=604800
      - CONTAINER_NAME=ephemeral_relay
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock

  homesteader_db:
    image: postgres:16.4
    container_name: homesteader_db

    # The container will create a user with this
    # UID/GID pair. This matches MY host, make them
    # match your host. This makes files created in
    # the mountpoint easily accessible for us
    user: ${USER_UID}:${USER_GID}

    environment:
      - POSTGRES_DB=nostr
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - PGDATA=/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nostrNet
    volumes:
      - /mnt/datadisk/volumes/nostr/homesteader_data:/var/lib/postgresql/data


