networks:
  bitnet_internal:
    driver: bridge
    name: bitnet_internal
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492b:fc78::/48

services:

  i2pd:
    image: purplei2p/i2pd
    restart: unless-stopped
    command:
      # Enable IPv6
      - '--ipv6'
      
      # Disbale IPv4
      # - '--ipv4=false'
      
      # Enable SAM
      - '--sam.enabled=1'
      - '--sam.address=::'
      - '--sam.port=${I2P_SAM_PORT}'
    networks:
      - mainNet


  bitcoind:
    extends:
      file: ../../services/bitcoin/compose.yml
      service: bitcoin
    build:
      args:
        - NPROC=2
    command:
      # Setup a tunnel via i2pd so
      # that we can make outbound
      # connections
      - '-i2psam=i2pd:${I2P_SAM_PORT}'

      # Also accept inbound i2p
      # connections
      - '-i2pacceptincoming'
    ports:
      # P2P connection
      - 8334:8334/tcp
    networks:
      # For talking with Electrum
      - bitnet_internal
      - mainNet

  # TODO: Setup i2pd here so that
  # it can be accessed and configured
  # via bob for peering

  # TODO: Move to `../../services/electrs/compose.yml`
  electrum:
    image: ghcr.io/deavmi/electrs:master
    restart: unless-stopped
    environment:
      # Set environment variables which
      # are used in the custom image to
      # switch the effective uid/gid
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      
      - "ELECTRS_ELECTRUM_RPC_ADDR=[::]:50001"
      - ELECTRS_DB_DIR=/data
      - ELECTRS_COOKIE_FILE=/cookieDir/${BITCOIN_COOKIE_FILE}
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:8332
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:8333

      - ELECTRS_NETWORK=bitcoin

       # TODO: Change later (TODO: make default if not set as well too)
      - ELECTRS_LOG_FILTERS=INFO
    # networks:
      # For talking to bitcoind
      # - bitnet_internal
    volumes:
      - ${ELECTRUM_DATA_DIR}:/data
      - ${ELECTRUM_COOKIES_DIR}:/cookieDir
    networks:
      - mainNet
    ports:
      - "${ELECTRUM_PORT}:50001/tcp"
      - ${ELECTRUM_METRICS_PORT}:4224/tcp
