networks:
  bitnet_internal:
    driver: bridge
    name: bitnet_internal
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492b:fc78::/48

services:
  bitcoind:
    extends:
      file: ../../services/bitcoin/compose.yml
      service: bitcoin
    build:
      args:
        - NPROC=2
    ports:
      # P2P connection
      - 8334:8334/tcp
    networks:
      # For talking with Electrum
      - bitnet_internal
      - mainNet

  # TODO: Setup i2pd here so that
  # it can be accessed and configured
  # via bob for peering

  # TODO: Move to `../../services/electrs/compose.yml`
  electrum:
    image: ghcr.io/deavmi/electrs:master
    restart: unless-stopped
    environment:
      # Set environment variables which
      # are used in the custom image to
      # switch the effective uid/gid
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      
      - ELECTRS_ELECTRUM_RPC_ADDR="electrum:50001"
      - ELECTRS_DB_DIR=/data
      - ELECTRS_COOKIE_FILE=/cookieDir/${BITCOIN_COOKIE_FILE}
      - ELECTRS_DAEMON_RPC_ADDR=bitcoind:8332
      - ELECTRS_DAEMON_P2P_ADDR=bitcoind:8333

      - ELECTRS_NETWORK=bitcoin

       # TODO: Change later (TODO: make default if not set as well too)
      - ELECTRS_LOG_FILTERS=INFO
    # networks:
      # For talking to bitcoind
      # - bitnet_internal
    volumes:
      - ${ELECTRUM_DATA_DIR}:/data
      - ${ELECTRUM_COOKIES_DIR}:/cookieDir
    networks:
      - mainNet
    ports:
      - "${ELECTRUM_PORT}:50001/tcp"
