services:
  chatmail-relay:
    container_name: chatmail_relay
    restart: unless-stopped
    image: ghcr.io/chatmail/docker:main
    user: ${USER_UID}:${USER_GID}
    environment:
      # Domain for the mail server (to generate certificates)
      - MAIL_DOMAIN=${CHATMAIL_DOMAIN}
    volumes:
      # Storage for mail
      # - ${CHATMAIL_STORAGE}:/opt/chatmail-www:z
    networks:
      ipv6_pool_net:
        ipv6_address: ${CHATMAIL_IPV6_ADDR}
      ygg_pool_net:
        ipv6_address: ${CHATMAIL_YGG_ADDR}
