secrets:
  MONERO_NODES:
    file: nodes.monero

services:
  monero:
    extends:
      file: ../../services/monero/compose.yml
      service: monero
    build:
      args:
        - NPROC=1
    env_file:
      - path: monero.secrets
        required: true
    networks:
      # ipv6_pool_net:
        # ipv6_address: ${MONERO_IPV6_ADDRESS}
      ygg_pool_net:
        ipv6_address: ${MONERO_YGG_ADDRESS}
    ports:
      - 18080/tcp
      - 18081/tcp

  monero_stats:
    image: ghcr.io/deavmi/monero-exporter
    network_mode: service:monero
    command:
      - "--bind-addr 9090"
      - "--monero-addr [::1]:18081"
      - "--telemetry-path /metrics"
    ports:
      - 9000/tcp
