secrets:
  MONERO_NODES:
    file: nodes.monero

services:
  monero:
    build:
      context: ../../images/monero/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    container_name: monero_daemon
    restart: always
    networks:
      - monnet
    secrets:
      - MONERO_NODES
    volumes:
      - type: bind
        source: ${MONERO_DATA_PATH}
        target: /data
    env_file:
      - path: monero.secrets
        required: true
    environment:
      # Maximum RPC connections from the same IP
      - MAX_CONNECTIONS=${MONERO_MAX_CONNECTIONS}

      # Set payment details for making use of the RPC
      # on this node
      - RPC_PAYMENT_WALLET_ADDR=${MONERO_RPC_PAYMENT_WALLET_ADDR}
      - RPC_PAYMENT_DIFFICULTY=${MONERO_RPC_PAYMENT_DIFFICULTY}
      - RPC_PAYMENT_CREDITS=${MONERO_RPC_PAYMENT_CREDITS}
    ports:
      - 18080:18080/tcp
      - 18081:18081/tcp
