secrets:
  MONERO_NODES:
    file: nodes.monero

services:
  monero:
    extends:
      file: ../../services/monero/compose.yml
      service: monero
    build:
      args:
        - NPROC=2
    env_file:
      - path: monero.secrets
        required: true
    networks:
      - mainNet
    ports:
      - 18080:18080/tcp
      - 18081:18081/tcp
