services:
  rrcd:
    container_name: rrcd
    restart: unless-stopped
    depends_on:
      - reticulum
    build:
      context: ../../../images/rrc
    environment:
      # AutoPeering over link-local didn't work
      # if you didn't make startup wait a little
      # bit (clearly for some Docker networking interfaces
      # to properly initialize)
      - SLEEP_TIME=5

      # Logging level
      - LOG_LEVEL=${RRCD_LOG_LEVEL:-INFO}

      # Announce interval in sconds (Default: 900 seconds)
      - ANNOUNCE_PERIOD=${RRCD_ANNOUNCE_INTERVAL:-900}

      # Hub name
      - HUB_NAME=${RRCD_HUB_NAME:-MyHub}

      # Greeting
      - GREETING=${RRCD_GREETING:-Bom dia}
    volumes:
      # State storage
      - ${RRCD_STATE_DIR}:/rrcd/state:z

      # Identity storage
      - ${RRCD_IDENTITY_DIR}:/rrcd/identity:z

      # Room registry
      - ${RRCD_ROOM_REGISTRY}:/rrcd/roomsReg:z
      
      # Reticulum state storage
      - ${RRCD_RETICULUM_HOME}:/rrcd/reticulum:z

      # Path to RRCD config file
      - ${RRCD_CONFIG_PATH}:/config.toml:z,ro
    user: ${USER_UID}:${USER_GID}
    networks:
      ipv6_pool_net:
        ipv6_address: ${RRCD_IPV6_ADDR}
      yggdrasil_net:
        ipv6_address: ${RRCD_YGG_IPV6_ADDR}
