services:
  monero:
    build:
      context: ../../images/monero/
      args:
        - NPROC=2
    container_name: monero_daemon
    restart: always
    secrets:
      - MONERO_NODES
    user: ${USER_UID}:${USER_GID}
    volumes:
      - type: bind
        source: ${MONERO_DATA_PATH}
        target: /data
    environment:
      # Maximum RPC connections from the same IP
      - MAX_CONNECTIONS=${MONERO_MAX_CONNECTIONS}

      # Set payment details for making use of the RPC
      # on this node
      - RPC_PAYMENT_WALLET_ADDR=${MONERO_RPC_PAYMENT_WALLET_ADDR}
      - RPC_PAYMENT_DIFFICULTY=${MONERO_RPC_PAYMENT_DIFFICULTY}
      - RPC_PAYMENT_CREDITS=${MONERO_RPC_PAYMENT_CREDITS}

      # Logging
      - LOG_LEVEL=${MONERO_LOG_LEVEL-0}
      - LOG_FILE=${MONERO_LOG_FILE-bitmonero.log}
