services:
  act-runner:
    # image: gitea/act_runner:latest
    build:
      context: .
    container_name: act_runner
    environment:
      # URL to your Gitea instance
      - GITEA_INSTANCE_URL=${ACT_GITEA_INSTANCE_URL}

      # Secret token (for accessing instance)
      # - GITEA_RUNNER_REGISTRATION_TOKEN=${ACT_GITEA_RUNNER_REGISTRATION_TOKEN}

      # Name this runner should report to Gitea
      - GITEA_RUNNER_NAME=${ACT_GITEA_RUNNER_NAME}

      # Labels we will report we support to Gitea
      - GITEA_RUNNER_LABELS=${ACT_GITEA_RUNNER_LABELS}
    # command:
      # - daemon
      # - --config
      # - /config.yml
    networks:
      - mainNet
    volumes:
      # Needs access to the docker socket so it
      # can control docker and spawn new instances
      # for CI jobs
      - /var/run/docker.sock:/var/run/docker.sock

      # Data directory
      - "${ACT_DATA_DIR}:/data:z"
