services:
  act-runner:
    # image: gitea/act_runner:latest
    build:
      context: .
    container_name: act_runner
    restart: unless-stopped
    environment:
      # URL to your Gitea instance
      - GITEA_INSTANCE_URL=${ACT_GITEA_INSTANCE_URL}

      # Name this runner should report to Gitea
      - GITEA_RUNNER_NAME=${ACT_GITEA_RUNNER_NAME}

      # Labels we will report we support to Gitea
      - GITEA_RUNNER_LABELS=${ACT_GITEA_RUNNER_LABELS}

      # The configuration file
      # - CONFIG_FILE=/config.yml
    env_file:
      # has Gitea runner secret inside
      - path: .runner
        required: true
    networks:
      - mainNet
    ports:
      - 9101:9101/tcp
    # user: ${USER_UID}:${DOCKER_GID}
    # group_add:
      # Add ourselves to the GID specified to allow us access
      # to the Docker socket that will be mounted inside our
      # container with the same GID as on the host side
      # - ${DOCKER_GID}
    volumes:
      # Needs access to the docker socket so it
      # can control docker and spawn new instances
      # for CI jobs
      # - /var/run/docker.sock:/var/run/docker.sock:rwz

      # Data directory
      - "${ACT_DATA_DIR}:/data:z"
