# FROM gitea/runner:nightly-dind-rootless AS base
# FROM gitea/runner:nightly-dind-rootless AS base
FROM docker.io/gitea/act_runner:latest


# Copy across configuration file
COPY config.yml /config.yml