services:
  # Go package datastore and proxy
  athens:
    image: gomods/athens:latest
    container_name: athens
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    networks:
      ipv6_pool_net:
        ipv6_address: ${ATHENS_IPV6_ADDR}
      ygg_pool_net:
        ipv6_address: ${ATHENS_YGG_ADDR}
    ports:
      - 3000
