services:
  # Yggmail auto
  yggmail:
    extends:
      file: ../../../services/yggmail-auto/compose.yml
      service: yggmail
    container_name: yggmail
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    # Place in same network namespace as `yggmail_tls`
    network_mode: service:yggmail_tls

  # Automatic TLS reverse proxy (with SNI)
  yggmail_tls:
    build:
      context: tls
    container_name: yggmail_tls
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    environment:
      # Ued to encrypt TLS secrets (FIXME: Determine what this is for)
      - TLSPROXY_PASSPHRASE=${YGGMAIL_TLS_PASSWORD}
    volumes:
      - ${YGGMAIL_TLS_CACHE_DIR}:/.cache:z
    networks:
      ipv6_pool_net:
        ipv6_address: ${IPV6_ADDR_TLS_YGGMAIL}
      ygg_pool_net:
        ipv6_address: ${YGG_ADDR_YGGMAIL}
    ports:
      # TLS endpoint
      - 1111/tcp

      # ACME must listen ALWAYS on port 80
      # (if you have conflicts then place)
      # this onto a seperate network
      - 80/tcp

      # Expose for non-TLS users (like over Yggdrasil)
      - 1143/tcp #IMAP
      - 1025/tcp #SMTP

  # RoundCube mail UI
  yggmail_ui:
    container_name: yggmail_ui
    image: roundcube/roundcubemail
    restart: unless-stopped
    depends_on:
      - yggmail
    user: ${USER_UID}:${USER_GID}
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=${YGGMAIL_UI_DOMAIN_IMAP}
      - ROUNDCUBEMAIL_SMTP_SERVER=${YGGMAIL_UI_DOMAIN_SMTP}

      # Point it to the YggMail instance
      - ROUNDCUBEMAIL_SMTP_PORT=1025
      - ROUNDCUBEMAIL_DEFAULT_PORT=1143
          
  # Reverse proxy with HTTPS for `gitea`
  yggmail_ui_proxy:
    build:
      context: flat/
    container_name: yggmail_ui_proxy
    restart: unless-stopped
    depends_on:
      - yggmail_ui
    # Run in same network namespace as `gitea`
    # so that we can bind to its network interface
    network_mode: service:yggmail_ui
    environment:
      - "DOMAIN=${YGGMAIL_UI_DOMAIN}"
      - "WHERE_TO_ADDR=[::1]"
      - "WHERE_TO_PORT=80"
      - "DEBUG_LEVEL=INFO"
    networks:
      ipv6_pool_net:
        ipv6_address: ${YGGMAIL_UI_IPV6}
      ygg_pool_net:
        ipv6_address: ${YGGMAIL_UI_YGG}
    ports:
      # Expose https and http
      - 443/tcp
      - 80/tcp
