networks:
  mainNet:
    driver: bridge
    name: mainNet
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492a:fc7f::/48

services:
  host-statistics:
    extends:
      file: ../../services/node_exporter/compose.yml
      service: statistics

  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    network_mode: "host"

  # TODO: This will be deployed on another machine
  act-runner:
    extends:
      file: ../../services/act_runner/compose.yml
      service: act-runner
    container_name: act
