networks:
  gitea_db_net:
    driver: bridge
    name: gitea_db_net
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492b:fc7f::/48
  gitea_redis_net:
    driver: bridge
    name: gitea_redis_net
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:452b:fc7f::/48

volumes:
  redis_gitea_data:

services:
  gitea:
    extends:
      file: ../../services/gitea/compose.yml
      service: gitea
    build:
      context: gitea/
    container_name: gitea
    depends_on:
      - db-gitea
      - minio
      - redis-gitea
    env_file:
      - path: .gitea
        required: true
    environment:
      # Gitea DB configuraiton
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db-gitea:5432
      - FORGEJO__database__NAME=${GITEA_DB_NAME}
      - FORGEJO__database__USER=${GITEA_DB_USER}
      - FORGEJO__database__PASSWD=${GITEA_DB_PASS}

      # Server settings
      - FORGEJO__server__ROOT_URL=/git/

      # Instance settings
      - FORGEJO__APP_NAME=DForge1
      - FORGEJO__ui0x2Emeta__AUTHOR=Deavmi's Forge
      - FORGEJO__ui0x2Emeta__DESCRIPTION=Where code is grinded out ⚙️
      - FORGEJO__ui__DEFAULT_THEME=forgejo-dark
      
      - FORGEJO__security__INSTALL_LOCK=true # Perform installation unattended

      # For session management
      - FORGEJO__session__PROVIDER=redis
      - FORGEJO__session__PROVIDER_CONFIG=redis://redis-gitea:6379
      - FORGEJO__session__COOKIE_NAME=gitea-cookie

      # For cache management
      - FORGEJO__cache__ADAPTER=redis
      - FORGEJO__cache__HOST=redis://redis-gitea:6379

      # MinIO storage
      - FORGEJO__storage__STORAGE_TYPE=minio
      - FORGEJO__storage__MINIO_BUCKET=gitea
      - FORGEJO__storage__MINIO_ENDPOINT=minio:9000

      # Logging configuration TODO: Maybe lower later
      - FORGEJO__log__LEVEL=Trace

      # For metrics
      - FORGEJO__metrics__ENABLED=true
    networks:
      - mainNet
      - gitea_db_net
      - minio_net
      - gitea_redis_net
  
  db-gitea:
    extends:
      file: ../../services/postgres/compose.yml
      service: db
    container_name: gitea_db
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME}
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASS}

    volumes:
      # Path for Postgres to store data
      - "${GITEA_POSTGRES_PATH}:/var/lib/postgresql/data:z"
    networks:
      - gitea_db_net

  # TODO: This should be a redis we use for ALL
  # our services then
  redis-gitea:
    image: redis:latest
    container_name: redis-gitea
    restart: unless-stopped
    volumes:
      # For Redis persistence
      - redis_gitea_data:/data:z
    networks:
      - gitea_redis_net
    
