volumes:
  redis_gitea_data:

services:

  # Reverse proxy with HTTPS for `gitea_old`
  gitea_old_web:
    build:
      context: flat/
    container_name: gitea_old_web
    depends_on:
      - gitea_old
    # Run in same network namespace as `gitea_old`
    # so that we can bind to its network interface
    network_mode: service:gitea_old
    environment:
      - "DOMAIN=${GITEA_OLD_DOMAIN}"
      - "WHERE_TO_ADDR=gitea_old"
      - "WHERE_TO_PORT=3000"

  # Actual Gitea service `gitea_old`
  gitea_old:
    build:
      context: gitea_old/
    container_name: gitea_old
    depends_on:
      - redis-gitea
      - minio
    networks:
      ipv6_pool_net:
        ipv6_address: ${GITEA_OLD_IPV6_ADDR}
    env_file:
      # has JWT token inside
      - path: .gitea.old
        required: true
      # Has minio settings inside
      - path: .gitea
        required: true
    environment:
      - USER_UID=1000
      - USER_GID=1000

      # Instance settings
      - GITEA__APP_NAME=DGitea1
      - GITEA__ui0x2Emeta__AUTHOR=Deavmi's (Old) Forge
      - GITEA__ui0x2Emeta__DESCRIPTION=Grandpa code 👴️

      
      # Gitea DB configuraiton
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__DB_PATH=/data/gitea/gitea.db
      - GITEA__database__DB_NAME=gitea

      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__lfs__PATH=/data/git/lfs

      # Server settings
      - GITEA__server__APP_DATA_PATH=/data/gitea
      - GITEA__server__DOMAIN=${GITEA_OLD_DOMAIN}
      - GITEA__server__SSH_DOMAIN=${GITEA_OLD_DOMAIN}
      - GITEA__server__HTTP_ADDR=${GITEA_OLD_IPV6_ADDR}
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=/
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__SSH_PORT=${GITEA_OLD_SSH_PORT}
      - GITEA__server__SSH_LISTEN_PORT=${GITEA_OLD_SSH_PORT}
      - GITEA__server__START_SSH_SERVER=true

      # For session management
      - GITEA__session__PROVIDER=redis
      - GITEA__session__PROVIDER_CONFIG=redis://redis-gitea:6379
      - GITEA__session__COOKIE_NAME=gitea-old-cookie

      # For cache management
      - GITEA__cache__ADAPTER=redis
      - GITEA__cache__HOST=redis://redis-gitea:6379

      # Automatic install based on environment varables
      - GITEA__security__INSTALL_LOCK=true

      # MinIO storage
      - GITEA__storage__STORAGE_TYPE=minio
      - GITEA__storage__MINIO_BUCKET=giteaold
      - GITEA__storage__MINIO_ENDPOINT=minio:9000

      # Logging configuration TODO: Maybe lower later
      - GITEA__log__LEVEL=Trace

      # For metrics
      - GITEA__metrics__ENABLED=true
    volumes:
      - ${GITEA_OLD_DATA_PATH}:/data:z
    # In this case it means allow access (firewalling rule)
    ports:
      # SSH server
      - ${GITEA_OLD_SSH_PORT}/tcp

      # Reverse proxy (on behalf of `gitea_old_web`)
      - "80/tcp"
      - "80/udp"
      - "443/tcp"
      - "443/udp"

  # Reverse proxy with HTTPS for `gitea`
  gitea_web:
    build:
      context: flat/
    container_name: gitea_web
    depends_on:
      - gitea
    # Run in same network namespace as `gitea`
    # so that we can bind to its network interface
    network_mode: service:gitea
    environment:
      - "DOMAIN=${GITEA_NEW_DOMAIN}"
      - "WHERE_TO_ADDR=gitea"
      - "WHERE_TO_PORT=3000"

  gitea:
    extends:
      file: ../../services/gitea/compose.yml
      service: gitea
    build:
      context: gitea/
    container_name: gitea
    depends_on:
      - db-gitea
      - minio
      - redis-gitea
    # Has minio settings inside
    env_file:
      - path: .gitea
        required: true
    environment:
      # Gitea DB configuraiton
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db-gitea:5432
      - FORGEJO__database__NAME=${GITEA_DB_NAME}
      - FORGEJO__database__USER=${GITEA_DB_USER}
      - FORGEJO__database__PASSWD=${GITEA_DB_PASS}

      # Server settings
      - FORGEJO__server__ROOT_URL=/
      - FORGEJO__server__DOMAIN=${GITEA_NEW_DOMAIN}

      # Instance settings
      - FORGEJO__APP_NAME=DForge1
      - FORGEJO__ui0x2Emeta__AUTHOR=Deavmi's Forge
      - FORGEJO__ui0x2Emeta__DESCRIPTION=Where code is grinded out ⚙️
      - FORGEJO__ui__DEFAULT_THEME=forgejo-dark

      # Forgejo actions
      - FORGEJO__ACTIONS__ENABLED=true
      - FORGEJO__ACTIONS__LOG_RETENTION_DAYS=365
      - FORGEJO__ACTIONS__ARTIFACT_RETENTION_DAYS=90

      # Federation
      - FORGEJO__FEDERATION__ENABLED=true
      - FORGEJO__FEDERATION__SHARE_USER_STATISTICS=true

      # SSH server
      - FORGEJO__server__DISABLE_SSH=false
      - FORGEJO__server__SSH_PORT=${GITEA_NEW_SSH_PORT}
      - FORGEJO__server__SSH_DOMAIN=${GITEA_NEW_DOMAIN}
      - FORGEJO__server__HTTP_ADDR=${GITEA_NEW_IPV6_ADDR}
      - FORGEJO__server__HTTP_PORT=3000
      - FORGEJO__server__SSH_LISTEN_PORT=${GITEA_NEW_SSH_PORT}
      - FORGEJO__server__START_SSH_SERVER=true

      # Automatic install based on environment varables
      - FORGEJO__security__INSTALL_LOCK=true

      # For session management
      - FORGEJO__session__PROVIDER=redis
      - FORGEJO__session__PROVIDER_CONFIG=redis://redis-gitea:6379
      - FORGEJO__session__COOKIE_NAME=gitea-cookie

      # For cache management
      - FORGEJO__cache__ADAPTER=redis
      - FORGEJO__cache__HOST=redis://redis-gitea:6379

      # MinIO storage
      - FORGEJO__storage__STORAGE_TYPE=minio
      - FORGEJO__storage__MINIO_BUCKET=gitea
      - FORGEJO__storage__MINIO_ENDPOINT=minio:9000

      # Logging configuration TODO: Maybe lower later
      - FORGEJO__log__LEVEL=Trace

      # For metrics
      - FORGEJO__metrics__ENABLED=true
    networks:
      ipv6_pool_net:
        ipv6_address: ${GITEA_NEW_IPV6_ADDR}
    # In this case it means allow access (firewalling rule)
    ports:
      # SSH server
      - ${GITEA_NEW_SSH_PORT}/tcp

      # Reverse proxy (on behalf of `gitea_web`)
      - "80/tcp"
      - "80/udp"
      - "443/tcp"
      - "443/udp"
  
  db-gitea:
    extends:
      file: ../../services/postgres/compose.yml
      service: postgres
    container_name: gitea_db
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME}
      - POSTGRES_USER=${GITEA_DB_USER}
      - POSTGRES_PASSWORD=${GITEA_DB_PASS}
    # Set effective UID/GID
    user: ${USER_UID}:${USER_GID}
    volumes:
      # Path for Postgres to store data
      - "${GITEA_POSTGRES_PATH}:/var/lib/postgresql/data:z"
    networks:
      ipv6_pool_net:
        ipv6_address: 2a04:5b81:2010:200a::105

  # TODO: This should be a redis we use for ALL
  # our services then
  redis-gitea:
    image: redis:latest
    container_name: redis-gitea
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    volumes:
      # For Redis persistence
      - ${GITEA_REDIS_DATA_PATH}:/data:z
    networks:
      ipv6_pool_net:
        ipv6_address: 2a04:5b81:2010:200a::104
    
