services:
  i2pd:
    extends:
      file: ../../services/i2pd/compose.yml
      service: i2pd
    build:
      additional_contexts:
        tunnelsconfig: ./i2pd
      args:
        - NPROC=1
    # FIXME: Enable yggdrasil (somehow)
    # maybe by placing an Yggdrasil instance
    # here and putting them on the same `ns`
    command:
      - "--datadir=/data"
      # - "--conf=/conf/i2pd.conf"
      - "--tunnelsdir=/tunnels"
      - "--tunconf=/tunnels"

      - "--loglevel=debug"

      - "--ipv4=false"
      - "--ipv6=true"
      # - "--meshnets.yggdrasil=true"
      # - "--meshnets.yggaddress=201:efe0:d45f:f82e:623c:a518:1f96:72bd"
      - "--floodfill"
    networks:
      ipv6_pool_net:
        ipv6_address: ${I2PD_IPV6_ADDR}
      # TODO: For Yggdrasil we mayneed to place
      # this into the same network namespace so
      # that i2pd can bind to the tun0 interface
      # TODO: Actually maybe not if host mode
      # is fine
    volumes:
      # Router data, all stuff that can be
      # deleted but is useful for caching
      - "${I2PD_DATA_DIR}:/data:z"
      
      # Configuration base path
      - "${I2PD_CONF_DIR}:/conf:z"
      
      # Tunnel key files
      - "${I2PD_KEYS_DIR}:/keys:z"
    # FIXME: Enable the below so that
    # they are allowed via the firewall
    ports:
      # SSU2
      - "6245/tcp"

      # NTCP2
      - "6246/tcp"

      # Web console
      - "8182:8182/tcp"
