services:
  sshchat:
    extends:
      file: ../../services/sshchat/compose.yml
      service: sshchat
    networks:
      - mainNet
    ports:
      - "2000:2022/tcp"

  matterbridge:
    extends:
      file: ../../services/matterbridge/compose.yml
      service: matterbridge
    build:
      context: matterbridge/
    depends_on:
      - ircd
      - sshchat
    networks:
      - mainNet
