services:
  sshchat:
    extends:
      file: ../../services/sshchat/compose.yml
      service: sshchat
    networks:
      - mainNet
    ports:
      - "2000:2022/tcp"

  matterbridge:
    extends:
      file: ../../services/matterbridge/compose.yml
      service: matterbridge
    build:
      context: matterbridge/
    depends_on:
      - ircd
      - sshchat
    networks:
      - mainNet

  xmpp:
    build:
      context: ejabberd/
    container_name: xmpp
    env_file:
      # Bring in `REGISTER_ADMIN_PASSWORD`
      - path: .xmpp
        required: true
    environment:
      - EJABBERD_MACRO_ADMIN=admin@${XMPP_DOMAIN}
      - EJABBERD_MACRO_HOST=${XMPP_DOMAIN}
    networks:
      - mainNet
    volumes:
      # Database storage
      - ${XMPP_DATA_PATH}:/opt/ejabberd/database:z

      # Uploads storage
      - ${XMPP_UPLOADS_PATH}:/opt/ejabberd/upload:z
    ports:
      - "5222:5222/tcp"
      - "5269:5269/tcp"
      
      # HTTP (also used for ACME challenges)
      - "5280:5280/tcp"
      
      - "5443:5443/tcp"
