services:
  sshchat:
    extends:
      file: ../../services/sshchat/compose.yml
      service: sshchat
    networks:
      - mainNet
    ports:
      - "2000:2022/tcp"

  matterbridge:
    extends:
      file: ../../services/matterbridge/compose.yml
      service: matterbridge
    build:
      context: matterbridge/
    depends_on:
      - ircd
      - sshchat
    networks:
      - mainNet


  # Reverse proxy with HTTP just because
  # ejabberd cannot bind on port 80
  # (See: https://docs.ejabberd.im/admin/configuration/basic/#setting-up-acme)
  xmpp_acme_passthrough:
    build:
      context: im/ejabberd/passthrough
    container_name: xmpp_acme_passthrough
    network_mode: service:xmpp
    ports:
      # Allow on behalf of `xmpp`
      - "5222/tcp"
      - "5269/tcp"
      - "5280/tcp" # TODO: allow?
      - "5443/tcp"

      # Allow for ACME challenge
      - "80/tcp"
    environment:
      - "WHERE_TO_ADDR=[::1]"
      - "WHERE_TO_PORT=5280"

  # Ejabberd XMPP server
  xmpp:
    build:
      context: im/ejabberd/core/
    container_name: xmpp
    env_file:
      # Bring in `REGISTER_ADMIN_PASSWORD`
      - path: .xmpp
        required: true
    environment:
      - EJABBERD_MACRO_ADMIN=admin@${XMPP_DOMAIN}
      - EJABBERD_MACRO_HOST=${XMPP_DOMAIN}
    # Set effective uid/gid
    # TODO: Fix this and re-enable it
    # user: ${USER_UID}:${USER_GID}
    
    # Run in same network namespace as `xmpp_acme_passthrough`
    # so that we can bind to its network interface
    # and hence will use its IPv6 address
    #
    # The only reason we do it this way round
    # is for non-cyclic dependency management
    network_mode: service:xmpp_acme_passthrough
    volumes:
      # Database storage
      - ${XMPP_DATA_PATH}:/opt/ejabberd/database:z

      # Uploads storage
      - ${XMPP_UPLOADS_PATH}:/opt/ejabberd/upload:z

  # Redis for caching
  redis-xmpp:
    image: redis:latest
    container_name: redis-xmpp
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    volumes:
      # For Redis persistence
      - ${XMPP_REDIS_DATA_PATH}:/data:z
    # Run in same network name space as `xmpp`
    # therefore it can access this by connecting
    # to ::1 as they will be sharing the same
    # lo0
    networks:
      ipv6_pool_net:
        ipv6_address: ${XMPP_ADDR}
