services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    volumes:
      # Data storage path
      - ${MINIO_PATH}:/data:z
    env_file:
      - path: .minio
        required: true
    networks:
      ipv6_pool_net:
        ipv6_address: ${IPV6_INTERNAL_USE_MINIO_ADDR}
    # Set effective uid/gid
    user: ${USER_UID}:${USER_GID}
    command:
      - "server"
      - "/data"
      # TODO: Find a way to safely expose this
      # - "--console-address"
      # - ":9001"
