services:
  gitea:
    image: codeberg.org/forgejo/forgejo:11
    restart: unless-stopped
    environment:
      # For when creating files
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    volumes:
      # Mount for repository data
      - "${GITEA_DATA_PATH}:/data:z"
      
      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro,z
      - /etc/localtime:/etc/localtime:ro,z
