networks:
  mainNet:
    driver: bridge
    name: mainNet
    enable_ipv6: true
    enable_ipv4: false
    ipam:
      config:
        - subnet: fde4:492a:fc7f::/48

services:
  host-statistics:
    extends:
      file: ../../services/node_exporter/compose.yml
      service: statistics

  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    volumes:
      - "${YGGDRASIL_CONF_PATH}:/etc/yggdrasil.conf:ro,z"

  fetcher:
    container_name: fetcher
    build:
      context: fetcher/
    networks:
      - mainNet

  unbound:
    extends:
      file: ../../images/unbound/compose.yml
      service: unbound
    build:
      additional_contexts:
        zones: unbound/zones
        configs: unbound/configs
    depends_on:
      - fetcher
    container_name: unbound
    restart: unless-stopped
    networks:
      - mainNet
    volumes:
      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      # Directory containing control socket
      - "${UNBOUND_CTL_DIR}:/ctl"
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  unbound-statistics:
    depends_on:
      - unbound
    build:
      context: unbound_exporter
    container_name: unbound_statistics
    restart: unless-stopped
    networks:
      - mainNet
    volumes:
      # Control socket
      - "${UNBOUND_CTL_DIR}/:/unbd/"
    command: -unbound.ca "" -unbound.cert "" -unbound.host "unix:///unbd/unbound.ctl"
    ports:
      # OpenTelemetry port
      - "9167:9167/tcp"
