networks:
  mainNet:
    driver: bridge
    name: mainNet
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492a:fc7f::/48

services:
  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    volumes:
      - "${CONFIGURATION_PATH}:/etc/yggdrasil.conf:ro,z"
  
  unbound:
    build:
      context: unbound/
    container_name: unbound
    restart: unless-stopped
    networks:
      - mainNet
    volumes:
      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      # Directory containing control socket
      - /tmp/unbnd:/ctl
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  unbound-statistics:
    depends_on:
      - unbound
    build:
      context: unbound_exporter
    container_name: unbound_statistics
    networks:
      - mainNet
    volumes:
      # Control socket
      - /tmp/unbnd/unbound.ctl:/unbound.ctl
    command: -unbound.ca "" -unbound.cert "" -unbound.host "unix:///unbound.ctl"
    ports:
      # OpenTelemetry port
      - "9167:9167/tcp"
