networks:
  mainNet:
    driver: bridge
    name: mainNet
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:492a:fc7f::/48

services:
  
  unbound:
    build:
      context: unbound/
    container_name: unbound
    restart: unless-stopped
    networks:
      - mainNet
    volumes:
      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      # Directory containing control socket
      - /tmp/unbnd:/ctl
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    volumes:
      - "${CONFIGURATION_PATH}:/etc/yggdrasil.conf:ro,z"
