services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      # As it uses it as the upstream DNS resolver
      - unbound
    networks:
      ipv6_pool_net:
        ipv6_address: ${PIHOLE_IPV6_ADDR}
    volumes:
      # Copy in adlists
      - lists.txt:/etc/pihole/adlists.list:z
    environment:
      # Pihole upstream DNS servers
      - FTLCONF_dns_upstreams=${PIHOLE_DNS_UPSTREAMS}

      # Disable rate limits
      - FTLCONF_dns_rateLimit_count=0
      - FTLCONF_dns_rateLimit_interval=0

      # Allow queries from all IPs
      - FTLCONF_dns_listeningMode=ALL

      # User UID/GID (TODO: what for? need to mount storage for this to make sense)
      - PIHOLE_UID=${USER_UID}
      - PIHOLE_GID=${USER_GID}
    # Has WebUI pasword in it
    env_file:
      - path: .pihole
        required: true
    ports:
      # Allow through firewall (DNS)
      - 53/tcp
      - 53/udp

      # Allow through firewall (WebUI)
      - 443/tcp
