services:
  calibre:
    extends:
      file: ../../../services/calibre/compose.yml
      service: calibre

        

  # Reverse proxy with HTTPS for `calibre`
  calibre_ui_proxy:
    build:
      context: ../flat/
    container_name: calibre_ui_proxy
    restart: unless-stopped
    environment:
      - "DOMAIN=${CALIBRE_DOMAIN}"
      - "DOMAIN_1=${CALIBRE_DOMAIN_1}"
      - "DOMAIN_2=${CALIBRE_DOMAIN_2}"
      - "WHERE_TO_ADDR=[::1]"
      - "WHERE_TO_PORT=8181"
      - "DEBUG_LEVEL=INFO"
    networks:
      ipv6_pool_net:
        ipv6_address: ${CALIBRE_IPV6_ADDR}
      ygg_pool_net:
        ipv6_address: ${CALIBRE_YGG_ADDR}
    ports:
      # Expose https and http
      - 443/tcp
      - 80/tcp
