services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - mainNet
    volumes:
      # Path to directory holding configuration file
      # - "${PROMETHEUS_CONF_DIR}:/etc/prometheus:z"

      # Non-bind mount volume (for state)
      - "${PROMETHEUS_STATE_DIR}:/prometheus:z"
      # - prometheus_data:/prometheus
