services:
  gpodder:
    # TODO: Pin to a hash d2355fc998bc0d921e9ff6ec65f5bfe03ad01966ee6ced3f6cae9ed79c6c6870
    # image: xthursdayx/gpodder-docker:d2355fc998bc0d921e9ff6ec65f5bfe03ad01966ee6ced3f6cae9ed79c6c6870
    image: xthursdayx/gpodder-docker:latest
    container_name: gpodder
    restart: unless-stopped
    # Place in same network namespace as `gpodder_ui_proxy`
    network_mode: service:gpodder_ui_proxy
    user: ${USER_UID}:${USER_GID}
    volumes:
      # Config path
      - ${GPODDER_CONFIG_PATH}:/config:z
       # Downloads path
      - ${GPODDER_DOWNLOADS_PATH}:/downloads:z
    environment:
      - PUID=${USER_UID}
      - PGID=${USER_GID}
      - PASSWORD=${GPODDER_PASSWORD}

  # Reverse proxy with HTTPS for `gpodder`
  gpodder_ui_proxy:
    build:
      context: ui/
    container_name: gpodder_ui_proxy
    restart: unless-stopped
    environment:
      - "DOMAIN=${GPODDER_DOMAIN}"
      - "DOMAIN_1=${GPODDER_DOMAIN_1}"
      - "DOMAIN_2=${GPODDER_DOMAIN_2}"
      - "WHERE_TO_ADDR=[::1]"
      - "WHERE_TO_PORT=80"
      - "DEBUG_LEVEL=INFO"
    networks:
      ipv6_pool_net:
        ipv6_address: ${GPODDER_IPV6_ADDR}
      ygg_pool_net:
        ipv6_address: ${GPODDER_YGG_ADDR}
    ports:
      # Expose https and http
      - 443/tcp
      - 80/tcp
