# networks:
#   mainNet:
#     driver: bridge
#     name: novasRedesWebNet
#     enable_ipv6: true
#     enable_ipv4: false
#     ipam:
#       config:
#         - subnet: fde4:493b:fc7f::/48

services:
  novasredes_builder:
    container_name: novasredes_builder
    build:
      context: builder
      dockerfile: Dockerfile
    user: ${USER_UID}:${USER_GID}
    volumes:
      - /mnt/datadisk/volumes/novasredes:/data:z
    environment:
      # Directory to `git pull`+`hugo build .` in
      - DIRECTORY=/data

      # Refresh and build every 1 hour
      - RATE=3600
    networks:
      - mainNet
