[irc]
	[irc.pinewood]
		Server="pinewood.irc.bnet.eu.org:6667"
		Nick="bridgebot"

[[gateway]]
	name="general"
	enable=true

	[[gateway.inout]]
		account="irc.pinewood"
		channel="#general"

[[gateway]]
	name="tlang"
	enable=true
	
	[[gateway.inout]]
		account="irc.pinewood"
		channel="#tlang"

[[gateway]]
	name="yggdrasil"
	enable=true
	
	[[gateway.inout]]
		account="irc.pinewood"
		channel="#yggdrasil"
