services:
  builder:
    container_name: builder
    build:
      context: ../../images/builder/.
    restart: unless-stopped
    secrets:
      - BUILDER_TOKEN
    environment:
      # Fixes issue with the Python babel package
      # used by mkdocs
      - TZ=UTC
    volumes:
      # Where the generated websites our output to
      - "${BUILDER_OUTPUT}:/home/builder/dump"

      # Source to build websites from
      - "${BUILDER_SOURCE}:/home/builder/src"

      # Scripts directry
      - "${BUILDER_SCRIPTS_DIR}:/scripts"

      # Makes timezone and time information available
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
