networks:
  mainNet:
    driver: bridge
    name: mainNet
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:493b:fc7f::/48

include:
  - quassel.yml
  - bots.yml

services:
  host-statistics:
    extends:
      file: ../../services/node_exporter/compose.yml
      service: statistics
    container_name: host_statistics

  yggdrasil:
    extends:
      file: ../../services/yggdrasil/compose.yml
      service: yggdrasil
    container_name: yggdrasil

  # TODO: caddy definition and let us copy our caddy file
  # over using a custom image rather. This will allow us
  # to rebuild with a new configuration then and not
  # have to maintain it within a mount-point.
  web:
    container_name: web
    build:
      context: web/
    # depends_on:
      # - prometheus
      # - grafana
    networks:
      - mainNet
    volumes:
      # Data directory to serve static site files
      # from
      - /mnt/datadisk/volumes/web:/webroot:z
    environment:
      - DOMAIN=deavmi.assigned.network
    ports:
      - "[::]:80:80/tcp"
      - "[::]:80:80/udp" # TODO: Does quick run on non-HTTPS?
      - "[::]:443:443/tcp"
      - "[::]:443:443/udp"