networks:
  quassel_db_net:
    driver: bridge
    name: quassel_db_net
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:498b:fc7f::/48

# volumes:
  # quassel_core_data:
  # quassel_db_data:
  # quassel_web_data:

services:
  quassel:
    image: kalaksi/quassel
    container_name: quassel-core
    restart: unless-stopped

    depends_on:
      - quassel-db

    # Command-line arguments to give
    # to entrypoint executable
    command:
      - "--config-from-environment" # Use environment variables as config parameters
      - "--port=4242" # container-side port to listen on
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Etc/UTC


      # Database-related
      - DB_BACKEND=PostgreSQL
      - DB_PGSQL_USERNAME=quassel_user
      - DB_PGSQL_PASSWORD=quassel_pass
      - DB_PGSQL_DB=quassel
      - DB_PGSQL_HOSTNAME=quassel-db
      - DB_PGSQL_PORT=5432
    volumes:
      # TODO: Place to on-disk path
      # - quassel_core_data:/config
      # Configuration data
      - "${QUASSEL_CORE_DATA_PATH}:/config:z"
    networks:
      - mainNet
      - quassel_db_net
    ports:
      - 4242:4242

  # quassel-web:
    # image: lscr.io/linuxserver/quassel-web:arm64v8
    # container_name: quassel-web
    # restart: unless-stopped
    # depends_on:
      # - quassel-core
    # environment:
      # - PUID=1000
      # - PGID=1003
      # - TZ=Etc/UTC
      # - QUASSEL_CORE=quassel-core
      # - QUASSEL_PORT=4242
      # - URL_BASE=/quassel
    # volumes:
      # # TODO: Place to on-disk path
      # # - quassel_web_data:/config
      # # Configuration data
      # - "${QUASSEL_WEB_DATA_PATH}:/config:z"
    # networks:
      # - mainNet

  quassel-db:
    image: postgres
    container_name: quassel-db
    environment:
      - POSTGRES_USER=quassel_user
      - POSTGRES_PASSWORD=quassel_pass
      - POSTGRES_DB=quassel
    volumes:
      # TODO: Fill this up with an env var
      - "${QUASSEL_CORE_DB_PATH}:/var/lib/postgresql/data:z:z"
      # - quassel_db_data:/var/lib/postgresql/data:z
    networks:
      - quassel_db_net
