networks:
  quassel_db_net:
    driver: bridge
    name: quassel_db_net
    enable_ipv6: true
    ipam:
      config:
        - subnet: fde4:498b:fc7f::/48

services:
  quassel:
    image: kalaksi/quassel
    container_name: quassel
    restart: unless-stopped
    depends_on:
      - quassel-db

    # Bring in additionally
    env_file:
      - path: .quassel
        required: true

    # Command-line arguments to give
    # to entrypoint executable
    command:
      # - "${QUASSEL_CFG_ENV:+--config-from-environment}" # Use environment variables as config parameters
      - "--port=4242" # container-side port to listen on
      - "--configdir=/config"
      - "--select-backend=PostgreSQL"
    environment:
      # Database-related
      - DB_BACKEND=PostgreSQL
      - DB_PGSQL_USERNAME=quassel_user
      - DB_PGSQL_PASSWORD=quassel_pass
      - DB_PGSQL_DATABASE=quassel
      - DB_PGSQL_HOSTNAME=quassel-db
      - DB_PGSQL_PORT=5432

      # Container-specific for files created
      - "QUASSEL_UID=${USER_UID}"
      - "QUASSEL_GID=${USER_GID}"
    volumes:
      # TODO: Place to on-disk path
      # - quassel_core_data:/config
      # Configuration data
      - "${QUASSEL_CORE_DATA_PATH}:/config:z"
    networks:
      - mainNet
      - quassel_db_net
    ports:
      - 4242:4242

  quassel-db:
    image: postgres:latest
    container_name: quassel-db
    environment:
      - POSTGRES_USER=quassel_user
      - POSTGRES_PASSWORD=quassel_pass
      - POSTGRES_DB=quassel
    volumes:
      - "${QUASSEL_CORE_DB_PATH}:/var/lib/postgresql/data:z"
    networks:
      - quassel_db_net
