services:
  gitea-irc-bot:
    build:
      context: ../../images/gitea-irc-bot/
      args:
        # Branch to use
        - BRANCH=master
        
        # Commit hash to checkout
        - COMMIT=a527faaf40e4268142d823309189fbaa1ff07e09
    container_name: gitea-irc-bot
    restart: unless-stopped
