services:
  gitea-irc-bot:
    build:
      context: ../../images/gitea-irc-bot/
      args:
        # Branch to use
        - BRANCH=master
        
        # Commit hash to checkout
        - COMMIT=c8b5403159cbb6077508048845732c457e2fd572
    container_name: gitea-irc-bot
    restart: unless-stopped
    volumes:
      # Bot configuration
      - "${GITEA_IRC_BOT_CONFIG_PATH}:/config.json:z,ro"
    # Makes the configuration options in your `config.json`
    # easier with no need to push it through a custom
    # network
    network_mode: host
