services:
  gitea-irc-bot:
    build:
      context: ../../images/gitea-irc-bot/
      args:
        # Branch to use
        - BRANCH=master
        
        # Commit hash to checkout
        - COMMIT=1383a956c83ba6dd8f63a6a4f4e065ad51ed09e2
    container_name: gitea-irc-bot
    restart: unless-stopped
