services:
  bitcoin:
    build:
      context: ../../images/bitcoin/
      args:
        - NPROC=1
    container_name: bitcoin_daemon
    restart: always
    volumes:
      - type: bind
        source: ${BITCOIN_DATA_DIR}
        target: /data
      - type: bind
        source: ${BITCOIN_BLOCKS_DIR}
        target: /blocks
      - type: bind
        source: ${BITCOIN_COOKIES_DIR}
        target: /cookies
    environment:
      # Effective user/group uid/gid to run as
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      
      # RPC authentication
      - RPC_USERNAME=${BITCOIN_RPC_USERNAME}
      - RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
      - RPC_COOKIE_FILE=/cookies/${BITCOIN_COOKIE_FILE_NAME}
