{
 "title": "Disks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk usage",
   "type": "stat",
   "description": "Disk usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(    (sum by(server) (node_filesystem_size_bytes{job=\"Nodes\"}) - sum by(server)  (node_filesystem_avail_bytes{job=\"Nodes\"}))\n    /\n    sum by(server) (node_filesystem_size_bytes{job=\"Nodes\"})\n)*100\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(server) (rate(node_disk_written_bytes_total{job=\"Nodes\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Bytes read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(server) (rate(node_disk_read_bytes_total{job=\"Nodes\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}