{
 "title": "DNS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Network activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries per second",
   "type": "timeseries",
   "description": "Rate of queries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(unbound_queries_total{job=\"unbound\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Network activity",
   "type": "timeseries",
   "description": "Network activity for name server",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{job=\"Nodes\", server=\"nameserver\"}[$__rate_interval]))",
     "legendFormat": "RX {{server}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"Nodes\", server=\"nameserver\"}[$__rate_interval])) * -1",
     "legendFormat": "TX {{server}}"
    }
   ]
  },
  {
   "title": "Average recursion time",
   "type": "timeseries",
   "description": "Average time taking for DNS resolution requests (non nameserver auth) to perform",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_avg{job=\"unbound\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "DNS statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Basic stats",
   "type": "stat",
   "description": "Basic stats",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_queries_total{job=\"unbound\"}",
     "legendFormat": "Queries"
    },
    {
     "expr": "unbound_recursive_replies_total{job=\"unbound\"}",
     "legendFormat": "Recursive replies"
    },
    {
     "expr": "unbound_prefetches_total{job=\"unbound\"}",
     "legendFormat": "Prefetches"
    },
    {
     "expr": "unbound_cache_misses_total{job=\"unbound\"}",
     "legendFormat": "Cache misses"
    },
    {
     "expr": "unbound_cache_hits_total{job=\"unbound\"}",
     "legendFormat": "Cache hits"
    },
    {
     "expr": "unbound_expired_total{job=\"unbound\"}",
     "legendFormat": "Expired total"
    }
   ]
  },
  {
   "title": "Cache hits/misses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_cache_hits_total{job=\"unbound\"}",
     "legendFormat": "Hit"
    },
    {
     "expr": "unbound_cache_misses_total{job=\"unbound\"}",
     "legendFormat": "Miss"
    }
   ]
  }
 ]
}