{
 "title": "Docker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Container information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers running",
   "type": "gauge",
   "description": "Number of containers running per each node.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (engine_daemon_container_states_containers{job=\"Docker\", state=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers stopped",
   "type": "stat",
   "description": "Number of containers per each node that are stopped.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (engine_daemon_container_states_containers{job=\"Docker\", state=\"stopped\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Events rate",
   "type": "timeseries",
   "description": "Rate of events firing off",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(engine_daemon_events_total{job=\"Docker\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(engine_daemon_events_total{job=\"Docker\"})",
     "legendFormat": "Events"
    },
    {
     "expr": "sum(engine_daemon_health_checks_total{job=\"Docker\"})",
     "legendFormat": "Healthchecks"
    },
    {
     "expr": "sum(builder_builds_triggered_total{job=\"Docker\"})",
     "legendFormat": "Triggered builds"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(engine_daemon_health_checks_failed_total{job=\"Docker\"})",
     "legendFormat": "Failed healthchecks"
    },
    {
     "expr": "sum(builder_builds_failed_total{job=\"Docker\"})",
     "legendFormat": "Builds failed"
    }
   ]
  },
  { "title": "Host information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Release",
   "type": "piechart",
   "description": "Operating systems versions",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by(os) (engine_daemon_engine_info{job=\"Docker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "piechart",
   "description": "Versions for kernel",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kernel) (engine_daemon_engine_info{job=\"Docker\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}