{
 "title": "ISR",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# ISR\n\nThis is the **I**nternet **S**ervices **R**outer"
   }
  },
  { "title": "I2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Tunnels",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "i2p_router_tunnels_participating{job=\"isr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnels participating",
   "type": "stat",
   "description": "Number of tunnels we are participating in",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_tunnels_participating{job=\"isr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes totals",
   "type": "stat",
   "description": "Total amount of bytes transited through this node",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_net_bytes_total{job=\"isr\", direction=\"inbound\"}",
     "legendFormat": "RX"
    },
    {
     "expr": "i2p_router_net_bytes_total{job=\"isr\", direction=\"outbound\"}",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Tunnel success ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_tunnels_success_ratio{job=\"isr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "How long the router has been running",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_uptime_seconds{job=\"isr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bandwidth rates",
   "type": "stat",
   "description": "Rates of transfers in different time windows",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_net_bw_bytes_per_second{job=\"isr\", direction=\"inbound\"}",
     "legendFormat": "Inbound  last {{window}}"
    },
    {
     "expr": "i2p_router_net_bw_bytes_per_second{job=\"isr\", direction=\"outbound\"}",
     "legendFormat": "Outbound last {{window}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Peering information",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "i2p_router_netdb_activepeers{job=\"isr\"}",
     "legendFormat": "Active peers"
    },
    {
     "expr": "i2p_router_netdb_knownpeers{job=\"isr\"}",
     "legendFormat": "Known peers"
    }
   ]
  }
 ]
}