{
 "title": "Networking",
 "description": "Network statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network activity",
   "type": "timeseries",
   "description": "Network activity for nodes",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(server) (rate(node_network_receive_bytes_total{job=\"Nodes\"}[$__rate_interval]))",
     "legendFormat": "RX {{server}}"
    },
    {
     "expr": "sum by(server) (rate(node_network_transmit_bytes_total{job=\"Nodes\"}[$__rate_interval])) * -1",
     "legendFormat": "TX {{server}}"
    }
   ]
  },
  {
   "title": "TX/RX totals",
   "type": "stat",
   "description": "Totals for transmit and receive",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(server) (node_network_receive_bytes_total{job=\"Nodes\"})",
     "legendFormat": "RX {{server}}"
    },
    {
     "expr": "sum by(server) (node_network_transmit_bytes_total{job=\"Nodes\"})",
     "legendFormat": "TX {{server}}"
    }
   ]
  },
  {
   "title": "Dropped packets",
   "type": "timeseries",
   "description": "Dropped packets failing to transmit and received packets ultimately dropped",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(server) (rate(node_network_receive_drop_total{job=\"Nodes\"}[$__rate_interval]))",
     "legendFormat": "Drop RX {{server}}"
    },
    {
     "expr": "sum by(server) (rate(node_network_transmit_drop_total{job=\"Nodes\"}[$__rate_interval])) * -1",
     "legendFormat": "Drop TX {{server}}"
    }
   ]
  },
  {
   "title": "Multicast",
   "type": "timeseries",
   "description": "Multicast packets received",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(server) (rate(node_network_receive_multicast_total{job=\"Nodes\"}[$__rate_interval]))",
     "legendFormat": "RX {{server}}"
    }
   ]
  },
  {
   "title": "Interface flapping",
   "type": "timeseries",
   "description": "Flapping rate of interfaces, i.e. how often carrier has changed",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Flaps" } },
   "targets": [
    {
     "expr": "rate(node_network_carrier_changes_total{job=\"Nodes\"}[$__rate_interval])",
     "legendFormat": "{{device}} @ {{server}} "
    }
   ]
  },
  { "title": "VPNs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Yggdrasil network",
   "type": "stat",
   "description": "Yggdrasil network statistics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_packets_total{job=\"Nodes\", device=\"yggdrasil0\"}",
     "legendFormat": "RX {{server}}"
    },
    {
     "expr": "node_network_transmit_packets_total{job=\"Nodes\", device=\"yggdrasil0\"}",
     "legendFormat": "TX {{server}}"
    }
   ]
  },
  {
   "title": "Mycelium network",
   "type": "stat",
   "description": "Mycelium network statistics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_packets_total{job=\"Nodes\", device=\"mycelium0\"}",
     "legendFormat": "RX {{server}}"
    },
    {
     "expr": "node_network_transmit_packets_total{job=\"Nodes\", device=\"mycelium0\"}",
     "legendFormat": "RX {{server}}"
    }
   ]
  }
 ]
}