{
 "title": "NGINX",
 "description": "Monitoring for web servers.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Graph of active connections to all NGINX instances.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"NGINX\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "stat",
   "description": "Total values",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_accepted{job=\"NGINX\"})",
     "legendFormat": "Accepted"
    },
    {
     "expr": "sum(nginx_connections_handled{job=\"NGINX\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Server status",
   "type": "status-history",
   "description": "Whether servers are up or not",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_up{job=\"NGINX\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "stat",
   "description": "NGINX I/O statistics",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_connections_reading{job=\"NGINX\"})",
     "legendFormat": "Reading"
    },
    {
     "expr": "sum by() (nginx_connections_writing{job=\"NGINX\"})",
     "legendFormat": "Writing"
    },
    {
     "expr": "sum(nginx_connections_waiting{job=\"NGINX\"})",
     "legendFormat": "Waiting"
    }
   ]
  }
 ]
}