services:
  statistics:
    image: quay.io/prometheus/node-exporter:latest
    container_name: statistics
    command: '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
