services:
  i2pd:
    build:
      context: ../../images/i2pd/
      args:
        # Change these to the value of `id -u`
        # on your HOST
        - USER_UID=${USER_UID}
        # Change these to the value of `id -g`
        # on your HOST
        - USER_GID=${USER_GID}
    container_name: i2pd
    restart: unless-stopped
