services:
  i2pd:
    build:
      context: ../../images/i2pd/
      args:
        # Change these to the value of `id -u`
        # on your HOST
        - USER_UID=${USER_UID}
        # Change these to the value of `id -g`
        # on your HOST
        - USER_GID=${USER_GID}
    container_name: i2pd
    restart: unless-stopped
    environment:
      # Enable IPv6
      - ENABLE_IPV6=yes

      # HTTP web console
      - "CONSOLE__BIND_ADDR=::"
      - CONSOLE__BIND_PORT=7070
      - CONSOLE__ROOT=/i2pd
      
      # Makes timezone and time information available
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    ports:
      # SSU2
      - "6245:6245/tcp"

      # NTCP2
      - "6246:6246/tcp"