
# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: "::"

common:
  # Recommendation by caskd to get it working
  # in IPv6-only networks (otherwise it can't
  # find any AF_INET addresses on any of the
  # interfaces and it crashes)
  instance_addr: '::1'
  ring:
    instance_enable_ipv6: true # See above  
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks