services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: always

    # In order for us to detect devices over WiFi,
    # thread ec. we need to be placed onto the host
    # LAN
    network_mode: host

    # TODO: Add missing env var for timezone
    # TODO: Add privaleged mode (why?)
    # See: https://www.home-assistant.io/installation/linux

    # TODO: Do volumes
    volumes:

     # Access to the directory where DBUS places
     # the socket to the bus
     - /run/dbus:/run/dbus:ro,z
     
     # Copy in configuration file to container
     - "${HOME_ASSISTANT_CONF_PATH}:/config:z"

    # TODO: Do any caps (like for USB Zigbee)
    # cap_add:
      # Add capability for performing needed network
      # manipulation via the `/dev/tun` in order to
      # open tun adaptor
      # - NET_ADMIN
