services:
  
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    command:
      - serve
    volumes:
      # Storage
      - ${NTFY_DATA_PATH}:/var/cache/ntfy:z
      - ${NTFY_ETC_PATH}:/etc/ntfy:z
      - ${NTFY_AUTH_PATH}:/var/lib/ntfy:z
    environment:
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_ENABLE_LOGIN: true
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
    networks:
      - mainNet
    ports:
      - ${NTFY_PORT}:80/tcp
