services:
  rngit:
    build:
      context: ../../../images/rngit
      args:
        # Enable GAI fix
        - GAI_PREFER_IPV6=true
    container_name: rngit
    restart: unless-stopped
    user: ${USER_UID}:${USER_GID}
    networks:
      ipv6_pool_net:
        ipv6_address: ${RNGIT_IPV6_ADDR}
      ygg_pool_net:
        ipv6_address: ${RNGIT_YGG_ADDR}
    volumes:
      # Mount in the RNGit state directory
      - ${RNGIT_STATE_DIRECTORY}:/config:z
      
      # Mount in the configuration file (as read-only)
      - ./configs/config:/config/config:z,ro

      # Repositories store
      - ${RNGIT_REPOSITORIES_DIRECTORY}:/repositories:z

      # Reticulum node storage
      - ${RNGIT_RETICULUM_DIRECTORY}:/rns

      # Mount in the (RNS) configuration file (as read-only)
      - ./configs/rns:/rns/config:z,ro
